### ISSUE TITLE
Unclear from the documentation how to configure task to run it with custom properties

### ISSUE THREAD

**Issue by acierto** [dreamzmaster/gulp-sitespeedio#12]
Lack of documentation:

If you need to specify any options you can't run your task like it specified in the doc: 
`gulp.task('default', ['jshint', 'sitespeedio']);`

but then you need somehow to tell to gulp task to wait till sitespeedio finishes own job. 

If you don't want to look at sources of gulp-sitespeedio and especially if you are newbie in Gulp it can be tricky.

**Comment by therealmark** [comment]
+1

**Comment by dreamzmaster** [comment]
Thanks for the PR @acierto.
