### ISSUE TITLE
Release compatible to sitespeed 4.0

### ISSUE THREAD

**Issue by fsmaia** [dreamzmaster/gulp-sitespeedio#14]
Hi!

First of all, congratulations for the port, it is been really useful in my projects!

However I'm facing a problem. `sitespeed.io:3.x` uses internally `browsertime:0.x` and it has a inner dependency (`async-node-events`) that is downloaded from git:

https://github.com/sitespeedio/browsertime/blob/v0.12.3/package.json#L43

My CI runs through a proxy and can't download any external dependencies.

Fortunately this dependence was removed since `browsertime:1.x-beta`, and `sitespeed.io:4.x-beta` makes use of upgraded browsertime as well.

Could you make a secondary release in npm compatible with `sitespeed.io:4.x-beta`?

If you need any help I'm available.

Thanks so far!

**Comment by soulgalore** [comment]
We are releasing sitespeed.io 4.0 later this week, @dreamzmaster let me know if you need any help upgrading the plugin! I've updated the [grunt plugin](https://github.com/sitespeedio/grunt-sitespeedio) to the latest beta.

**Comment by priley86** [comment]
+1 - would love to see this upgraded to 4.0.

**Comment by dreamzmaster** [comment]
in progress with #15

**Comment by dreamzmaster** [comment]
Upgraded to sitespeed 4.x
