### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by labbydev** [dreamzmaster/gulp-sitespeedio#2]
Trying to run this on a local static site. Every time I run it (and I tried just using http://www.sitespeed.io) I get 0 passing,  0 failing. I was expecting the output to be the same as the output running sitespeed itself. However running through gulp I only get the budget.html and am missing the rest of the html, css, js, etc. Could you point me in the correct direction. My task below for reference:

gulp.task('speed-test', sitespeed({
  url: 'http://127.0.0.1/',
  deepth: 1,
  resultBaseDir: 'test-results',
  browser: 'chrome',
  connection: 'desktop',
  no: 6,
  showFailedOnly: true,
  budget: {
    rules: {
      default: 90
    },
    page: {
      image: 10,
      css: 1,
      requests: 7,
      pageWeight: 300000,
      jsWeight: 0
    },
    gpsi: {
      score: 96
    }
  }
}));

**Comment by dreamzmaster** [comment]
@labyrwa I just tried this configuration and results are absolutely fine, apart from generating all the HTMLs.

To generate the HTML as sitespeed, you need to add

```
html: true
```

**Comment by labbydev** [comment]
Thanks for the note about the html. That's working great now. But it's still not analyzing, when I look over the results it says 0 pages tested and all of the results are always "NaN (NaN)". I attached a screenshot of the results. 
![screen shot 2015-06-05 at 9 01 36 am](https://cloud.githubusercontent.com/assets/1653723/8007453/812726ce-0b61-11e5-8d3f-1bf90f90774e.png)

**Comment by raptor235** [comment]
I have the same issue... what's going on?

**Comment by vAugagneur** [comment]
Hi, did you find the solution ? @raptor235 or @labbydev
I have the same issue too
