### ISSUE TITLE
urls option

### ISSUE THREAD

**Issue by labbydev** [dreamzmaster/gulp-sitespeedio#3]
Right now the plugin shuts down when using urls option instead of the url option due to

if (!options.url) {
        throw new PluginError('gulp-sitespeedio', 'Missing url option to Analyse');
    }

**Comment by labbydev** [comment]
I'd recommend:

if (!options.url && !options.urls) {
        throw new PluginError('gulp-sitespeedio', 'Missing url option to Analyse');
    }

**Comment by dreamzmaster** [comment]
Thanks Sure will update!

**Comment by dreamzmaster** [comment]
Updated.
