### ISSUE TITLE
how can i use the gulp-sitespeedio to test some page if the page need to login?

### ISSUE THREAD

**Issue by qileilove** [dreamzmaster/gulp-sitespeedio#9]
i use gulp-sitespeedio  to test our website,the application has a login page. If I provide the application's url, if a valid user is not logged in the login page will be displayed. So how do I test performance using  gulp-sitespeedio? Is it possible to automate the login part?

**Comment by dreamzmaster** [comment]
Hi,
it will work when we release 4.0 but that will not be until June so there is some time until it happens, sorry. What's good is that it will work as you done already, check out the example here: 
https://github.com/tobli/browsertime/blob/1.0/test/preposttasks/preLoginExample.js

Follow that pattern and it will work.

For now you need to hack and send the cookie as a request headers.
